## Practice Task

In [1]:
import numpy as np

### Replace using Conditions


In [3]:
a=np.array([10,20,30,40,50])

a[a > 20] = 999

print(a)

[ 10  20 999 999 999]


### Masking
    Boolean arrays used for filtering

In [4]:
a=np.array([10,20,30,40,50])
mask=a >20
print(mask)

print(a[mask])

[False False  True  True  True]
[30 40 50]


### Modify using nditer

In [8]:
a=np.array([1,2,3])
for i in np.nditer(a,op_flags=['readwrite']):
    i[...]=i * 10
print(a)

[10 20 30]


### Structured Array

In [10]:
stu = np.array([
                ("Ram",21,80.5),
                ("Sham",24,79.5) ],
               dtype=[
                   ("name",'U10'),
                   ("age",'i4'),
                   ("marks",'f4')
               ]
              )
print(stu)

[('Ram', 21, 80.5) ('Sham', 24, 79.5)]


#### Access Column

In [12]:
print(stu['name']) # Name Column String

['Ram' 'Sham']


In [14]:
print(stu['age']) # Age Column Integer

[21 24]


In [16]:
print(stu['marks']) # Marks Column Float

[80.5 79.5]


#### Access Row

In [13]:
print(stu[0]) 

('Ram', 21, 80.5)


In [17]:
print(stu[1]) 

('Sham', 24, 79.5)


#### Access Single Value

In [18]:
print(stu[0]['name'])

Ram


In [20]:
print(stu[1]['name'])

Sham


In [22]:
print(stu[0]['marks'])

80.5


In [23]:
print(stu[1]['age'])

24


#### Modify Values

In [24]:
stu[0]['marks'] = 95

print(stu)

[('Ram', 21, 95. ) ('Sham', 24, 79.5)]


In [25]:
stu[0]['name'] = "SANDESH"

print(stu)

[('SANDESH', 21, 95. ) ('Sham', 24, 79.5)]


## Mini Project
    Student Marks

In [27]:
import numpy as np

marks = np.array([
    [78,85,90],
    [45,50,55],
    [88,92,95],
    [35,40,30]
])

print(marks)

[[78 85 90]
 [45 50 55]
 [88 92 95]
 [35 40 30]]


### Total Marks

In [35]:
total = np.sum(marks, axis=1)

print(total)

[253 150 275 105]


### Average Marks

In [49]:
average = np.mean(marks, axis=1)

print(average,"\n")

average = np.round(np.mean(marks, axis=1), 2)

print("Only 2 decimal places:\n",average)

[84.33333333 50.         91.66666667 35.        ] 

Only 2 decimal places:
 [84.33 50.   91.67 35.  ]


### Highest Marks

In [37]:
print(np.max(marks))

95


#### Lowest Marks

In [38]:
print(np.min(marks))

30


#### Passed Student
    Average is > 40

In [39]:
passed = average >= 40

print(passed)

[ True  True  True False]


### Bonus Marks = 5

In [40]:
bonus = marks + 5

print(bonus)

[[ 83  90  95]
 [ 50  55  60]
 [ 93  97 100]
 [ 40  45  35]]


#### Topper Student

In [41]:
topper = np.argmax(total)

print(topper) #Index 2 student is topper Because total=275

2


#### Sort Totals

In [42]:
print(np.sort(total)) #Ascending

[105 150 253 275]


In [43]:
print(np.sort(total)[: : -1]) #Descending

[275 253 150 105]


### SUMMURY

In [46]:
print("Totals:", total)

print("Average:", np.round(np.mean(marks, axis=1), 2))


print("Highest:", np.max(marks))

print("Lowest:", np.min(marks))

Totals: [253 150 275 105]
Average: [84.33 50.   91.67 35.  ]
Highest: 95
Lowest: 30
