## Numpy Statistical and Other Functions

In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

### Statistical Functions

#### 1.Mean()

In [3]:
print(np.mean(a))

30.0


#### 2.Median()

In [5]:
print(np.median(a))

30.0


#### 3.Sum()

In [7]:
print(np.sum(a))

150


#### 4.Min()

In [9]:
print(np.min(a))

10


#### 5.Max()

In [10]:
print(np.max(a))

50


#### 6.Standard Deviation- Std()
    Mesures spread of data from mean

In [11]:
print(np.std(a))

14.142135623730951


#### 7.Variance-Var()
    Mesuares data variability

In [12]:
print(np.var(a))

200.0


### Practice Task

In [13]:
import numpy as np

marks = np.array([78,85,90,67,88,92])

print("Mean:", np.mean(marks))

print("Median:", np.median(marks))

print("Sum:", np.sum(marks))

print("Minimum:", np.min(marks))

print("Maximum:", np.max(marks))

print("Standard Deviation:", np.std(marks))

print("Variance:", np.var(marks))

Mean: 83.33333333333333
Median: 86.5
Sum: 500
Minimum: 67
Maximum: 92
Standard Deviation: 8.556998435328957
Variance: 73.22222222222221


### Other Functions

#### 1.reshape()
    Changes shape of array without changing data

In [15]:
a6=np.array([1,2,3,4,5,6])
a6

array([1, 2, 3, 4, 5, 6])

##### 2 Rows And 3 Columns

In [17]:
b=a6.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

##### 3 Rows And 2 Columns

In [18]:
c=a6.reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 2.flatten()
    Converts multidimensional to 1D array

In [20]:
print(b.flatten())

[1 2 3 4 5 6]


#### 2.1 ravel()
    Same as flatten,But it is faster and efficient

In [22]:
print(b.ravel())

[1 2 3 4 5 6]


#### 3.transpose()
    Converts Rows into Columns and Viseversa

In [26]:
np.transpose(b)

array([[1, 4],
       [2, 5],
       [3, 6]])

##### Using T keyword

In [25]:
print(b.T)

[[1 4]
 [2 5]
 [3 6]]


### Practice Task

In [27]:
import numpy as np

a = np.arange(1,13)

print("Original Array:")
print(a)

b = a.reshape(3,4)

print("Reshaped Array:")
print(b)

print("Flatten:")
print(b.flatten())

print("Transpose:")
print(b.T)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Transpose:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Create array from 1 to 9 and reshape into 3x3.

In [28]:
a = np.arange(1,10)

print("Original Array:")
print(a)

b = a.reshape(3,3)

print("Reshaped Array 3x3:")
print(b)

Original Array:
[1 2 3 4 5 6 7 8 9]
Reshaped Array 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Convert 2D array into 1D array.

In [33]:
a=np.arange(1,13).reshape(4,3)
print("2D Array",a)

b=a.flatten()

print("1D Array:",b)

2D Array [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
