## Linear Algebra

In [1]:
import numpy as np

### 1.dot product
    dot() Multiplies arrays mathematically

In [3]:
a=np.array([1,2,3])
print(a)
b=np.array([4,5,6])
print(b)
print("Dot product:",np.dot(a,b))

[1 2 3]
[4 5 6]
Dot product: 32


### 2.Matrix Multiplecation 

In [9]:
a=np.array(
    [
        [1,2],
        [3,4]
    ])
b=np.array(  [
        [5,6],
        [7,8]
    ]
)
print(a)
print("\n",b,"\n")
print("Matrix Multiplecation:\n",np.matmul(a,b))

[[1 2]
 [3 4]]

 [[5 6]
 [7 8]] 

Matrix Multiplecation:
 [[19 22]
 [43 50]]


### 3.Determinant-det()
    It gives matrix value

In [10]:
a=np.array(
    [
        [1,2],
        [3,4]
    ])
print(a)
print("Determinant of a:",np.linalg.det(a))

[[1 2]
 [3 4]]
Determinant of a: -2.0000000000000004


### 4.Inverse matrix
    Returns opposite matrix mathematically
    Only square matrix can have inverse

### Practice Task

In [55]:
import numpy as np

a = np.array([
    [2,3],
    [1,4]
])

b = np.array([
    [5,6],
    [7,8]
])

print("Dot Product:")
print(np.dot([1,2],[3,4]))

print("Matrix Multiplication:")
print(np.matmul(a,b))

print("Transpose:")
print(a.T)

print("Determinant:")
print(np.linalg.det(a))

print("Inverse:")
print(np.linalg.inv(a))

Dot Product:
11
Matrix Multiplication:
[[31 36]
 [33 38]]
Transpose:
[[2 1]
 [3 4]]
Determinant:
5.000000000000001
Inverse:
[[ 0.8 -0.6]
 [-0.2  0.4]]


In [13]:
a=np.array(
    [
        [1,2],
        [3,4]
    ])
print("Matrix A:\n",a)
print("Inverse Matrix of a:\n",np.linalg.inv(a))

Matrix A:
 [[1 2]
 [3 4]]
Inverse Matrix of a:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### 5.trace()

    Returns sum of diagonal elements


In [14]:
a=np.array(
    [
        [1,2],
        [3,4]
    ])
print(a)
print("Sum of diagonal:",np.trace(a))

[[1 2]
 [3 4]]
Sum of diagonal: 5


### 6.diagonal()
    Returns diagonal elements

In [16]:
a=np.array(
    [
        [1,2],
        [3,4]
    ])
print(a)
print("Diagonal Elements:",np.diagonal(a))

[[1 2]
 [3 4]]
Diagonal Elements: [1 4]


### 7.rank()
    Tells independent row/columns count

In [18]:
a=np.array(
    [
        [1,2,3],
        [3,4,4],
        [5,6,8]
    ])
print(a)
print("Rank:",np.linalg.matrix_rank(a))

[[1 2 3]
 [3 4 4]
 [5 6 8]]
Rank: 3


### 8.Eigenvalues - eig()
    Special values related to matrix transformation

In [26]:
values,vectors=np.linalg.eig(a)
print(values)

[13.04140098 -0.6993033   0.65790233]


### 9.Eigenvectors - eig()
    Directions associated with eigenvalues

In [28]:
print(vectors) # function will give output at ones both

[[-0.28598745 -0.89929159  0.21858389]
 [-0.46545242  0.32485682 -0.82325055]
 [-0.8375949   0.29281851  0.52390802]]


### 10.solve()
    Solve Linear equations
    Ex:-  2x + y = 5
          x + y =3

In [31]:
a=np.array([
            [2,3],
            [1,1]
])
print("Array A:\n",a)
b=np.array([5,3])
print("Array B\n",b)
print("Results:",np.linalg.solve(a,b))

Array A:
 [[2 3]
 [1 1]]
Array B
 [5 3]
Results: [ 4. -1.]


### Practice Task

In [54]:
import numpy as np

a = np.array([
    [4,2],
    [1,3]
])

print("Trace:")
print(np.trace(a))

print("Diagonal:")
print(np.diagonal(a))

print("Rank:")
print(np.linalg.matrix_rank(a))

values, vectors = np.linalg.eig(a)

print("Eigenvalues:")
print(values)

print("Eigenvectors:")
print(vectors)

Trace:
7
Diagonal:
[4 3]
Rank:
2
Eigenvalues:
[5. 2.]
Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### Normal Python loop

In [32]:
N=[1,2,3,4,5]
res=[]
for i in N:
    res.append(i * 2)
res

[2, 4, 6, 8, 10]

## Vectorization 
    Performing operations on entire array without loops

In [33]:
a=np.array([1,2,3,4,5])
print(a * 2)

[ 2  4  6  8 10]


### Vectorization Arithmetic

In [51]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a + b)

print(a * b)

print(b - a)

print(b / a)


[5 7 9]
[ 4 10 18]
[3 3 3]
[4.  2.5 2. ]


### Universal Functions
    Functions that operate element-wise

### 1.sqrt()
    Square Root of Elements

In [35]:
a=np.array([2,4,16,121,169])
print(np.sqrt(a))

[ 1.41421356  2.          4.         11.         13.        ]


### 2.sin()
    Sin value of Elements

In [36]:
a=np.array([2,4,16,20])
print(np.sin(a))

[ 0.90929743 -0.7568025  -0.28790332  0.91294525]


### 3.log()
    Log value of elements

In [38]:
a=np.array([2,4,8,10])
print(np.log(a))

[0.69314718 1.38629436 2.07944154 2.30258509]


### 4.abs()
    Gives absulute value
    Negative value became a positive

In [41]:
a=np.array([2,4,-16,-23,-4])
print(np.abs(a))

[ 2  4 16 23  4]


### 5.pow()
    Gives power of elements

In [44]:
a=np.array([2,4,16,5,6,7])
print(np.pow(a,2))

[  4  16 256  25  36  49]


## Performance Comparison

In [49]:
import time
a=np.arange(10000)
start=time.time()

b=a * 2

end=time.time()

print(end-start)

0.00022554397583007812


### FUNCTION shuffle()
    shuffle array values randomly

In [53]:
a = np.array([1,2,3,4,5])

np.random.shuffle(a)

print(a)

[3 1 4 5 2]
