## Stacking || Splitting || Random Module

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b=np.array([4,5,6])
b

array([4, 5, 6])

### Stacking Functions

#### 1.hstack()
    Joins array Horizontly

In [4]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


#### 2.vstack()
    Joins array Vertically

In [5]:
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


#### 3.Concatenate()
    Combines arrays

In [7]:
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


### Splitting Functions
   

#### 1.split()
     Divides arrays into parts

In [8]:
c=np.array([1,2,3,4,5,6])
print(np.split(c,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


#### 2.hsplit()
    Horizontly split

In [16]:
d=np.arange(1,9).reshape(2,4)
print(d)
print("Horizontly:",np.hsplit(d,2))

[[1 2 3 4]
 [5 6 7 8]]
Horizontly: [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


#### 3.vsplit()
    Vertically

In [18]:
e=np.arange(1,9).reshape(4,2)
print(e)

print("Vertically:",np.vsplit(e,2))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Vertically: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


### Practice Task

In [19]:
import numpy as np

salary = np.array([25000,30000,35000])

bonus = np.array([2000,3000,4000])

print("Horizontal Stack:")
print(np.hstack((salary,bonus)))

print("Vertical Stack:")
print(np.vstack((salary,bonus)))

data = np.array([10,20,30,40,50,60])

print("Split Data:")
print(np.split(data,3))

Horizontal Stack:
[25000 30000 35000  2000  3000  4000]
Vertical Stack:
[[25000 30000 35000]
 [ 2000  3000  4000]]
Split Data:
[array([10, 20]), array([30, 40]), array([50, 60])]


### Random Module

#### 1.rand()
    Random decimal numbers from 0 and 1
    

In [20]:
print(np.random.rand(5))

[0.70530669 0.52618887 0.90252802 0.20566402 0.85601972]


#### 2.randint()
    Generates random integers

In [22]:
print(np.random.randint(1,10,5))

[9 4 9 3 3]


#### 3.randn()
    Random values from normal distribution

In [23]:
print(np.random.randn(5))

[-0.16557155 -1.01806304 -2.76113635 -0.39574468  0.3481135 ]


#### 4.choice()
    Select random values from list

In [25]:
colors=["Red","Blue","Green"]
print(np.random.choice(colors))

Green


#### 5.seed()
    Fixes Random Output or same output every time

In [27]:
np.random.seed(1)
print(np.random.randint(1,10,4))

[6 9 6 1]


### Practice Task

In [29]:
import numpy as np

marks = np.random.randint(35,100,10)

print("Student Marks:")
print(marks)

print("Average Marks:")
print(np.mean(marks))

print("Highest Marks:")
print(np.max(marks))

Student Marks:
[49 85 48 44 42 98 96 57 92 36]
Average Marks:
64.7
Highest Marks:
98
