#  50 NumPy Questions 

**Topics covered:** Array creation · Indexing & slicing · Math operations · Linear algebra · Statistics · Broadcasting · Random · Reshaping · Advanced tricks


In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.1.3


---
## 🟢 Section 1 — Array Creation (Q1–Q10)

### Q1. Create a 1-D array of integers from 10 to 49 (inclusive).

In [20]:
A=np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Q2. Create a 3×3 identity matrix.

In [12]:
A=np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Q3. Create a 5×5 array of zeros and set its border elements to 1 (interior stays 0).

In [19]:
ans = np.zeros((5, 5))
print("Original Array:\n",ans)
ans[[0, -1], :] = 1
ans[:, [0, -1]] = 1
print("\nChanged Array:\n",ans)

Original Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Changed Array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Q4. Create a 4×4 array with values ranging from 0 to 15 (reshape from arange).

In [23]:
a = np.arange(16).reshape(4, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Q5. Generate 6 evenly spaced values between 0 and 1 (inclusive) using `linspace`.

In [24]:
ans = np.linspace(0, 1, 6)
print(ans)

[0.  0.2 0.4 0.6 0.8 1. ]


### Q6. Create a 3×3 array of random floats in [0, 1). Set a fixed random seed of 42 first.

In [28]:
np.random.seed(42)
a=np.random.rand(3,3)
print(a)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


### Q7. Create an array of 10 random integers between 1 and 100 (inclusive).

In [37]:
np.random.seed(0)
ans = np.random.randint(1, 101, size=10)
print(ans)

[45 48 65 68 68 10 84 22 37 88]


### Q8. Create a 3×3 array filled with the value 7 (integer dtype).

In [39]:
a = np.full((3, 3), 7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Q9. Stack the two arrays `a = [1, 2, 3]` and `b = [4, 5, 6]` **vertically** to form a 2×3 matrix.

In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack([a,b]))


[[1 2 3]
 [4 5 6]]


### Q10. Create a checkerboard 8×8 pattern (alternating 0s and 1s) using `tile` or slicing.

In [ ]:
# Your answer here


In [42]:
ans = np.zeros((8, 8), dtype=int)
ans[1::2, ::2] = 1
ans[::2, 1::2] = 1
print(ans)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


---
## 🟡 Section 2 — Indexing & Slicing (Q11–Q20)

### Q11. Given `arr = np.arange(1, 26).reshape(5, 5)`, extract the sub-matrix formed by rows 1–3 and columns 2–4.

In [5]:
arr = np.arange(1, 26).reshape(5, 5)
print("Original Array:\n",arr)

a=arr[1:4,2:5]

print("formed Array:\n",a)

Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
formed Array:
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]


### Q12. From `arr = np.arange(20)`, replace all even values with -1 (in-place).

In [6]:
arr = np.arange(20)
print("Original Array:\n",arr)

arr[arr % 2 == 0] = -1
print("Formed Array:\n",arr)


Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Formed Array:
 [-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19]


### Q13. From `arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])`, return the indices that would sort it.

In [5]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
ans = np.sort(arr)
print("Elements:\n",ans)
ans = np.argsort(arr)
print("Indexes:\n",ans)


Elements:
 [1 1 2 3 4 5 6 9]
Indexes:
 [1 3 6 0 2 4 7 5]


### Q14. Using fancy indexing, select elements at positions (0,0), (1,2), (2,1) from a 3×3 array.

In [3]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
rows = [0, 1, 2]
cols = [0, 2, 1]
ans = arr[rows, cols]
print(ans)  


[10 60 80]


### Q15. Reverse the rows of a 5×5 random integer matrix (flip upside-down, no loop).

In [7]:
np.random.seed(1)
arr = np.random.randint(0, 10, (5, 5))
print('Original:\n', arr)

ans = arr[::-1]
print("Reverse Formed:\n", ans)


Original:
 [[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
Reverse Formed:
 [[1 7 0 6 9]
 [2 4 7 7 9]
 [2 4 5 2 4]
 [0 1 7 6 9]
 [5 8 9 5 0]]


### Q16. From a 1-D array, find all values greater than 15 **without** a loop.

In [8]:
arr = np.array([5, 18, 3, 22, 10, 16, 7, 30])

a= arr[arr > 15]

print(a)


[18 22 16 30]


### Q17. Get the unique values **and** their counts from the array `[1,2,2,3,3,3,4,4,4,4]`.

In [13]:
arr = np.array([1,2,2,3,3,3,3,4,4,4,4,4])

vals, counts = np.unique(arr, return_counts=True)

print("Unique values:\n",vals)

print("Counts:\n",counts)

Unique values:
 [1 2 3 4]
Counts:
 [1 2 4 5]


### Q18. Clip all values in `arr` to be within [10, 50].

In [14]:
arr = np.array([5, 10, 25, 55, 80, 40, 2])

ans = np.clip(arr, 10, 50)
print(ans)

[10 10 25 50 50 40 10]


### Q19. Use `np.where` to replace negatives with 0 and positives with 1 in a mixed array.

In [15]:
arr = np.array([-3, 7, -1, 0, 5, -9, 2])

ans = np.where(arr >= 0, 1, 0)

print(ans)

[0 1 0 1 1 0 1]


### Q20. Delete every other column from a 4×6 matrix (keep columns 0, 2, 4).

In [18]:
arr = np.arange(24).reshape(4, 6)
print('Original:\n', arr)
ans = arr[:, ::2]

print("formed Array:\n",ans)

Original:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
formed Array:
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]


In [ ]:
# ✅ Solution
# 

---
## 🟠 Section 3 — Math & Statistics (Q21–Q30)

### Q21. Normalize a 1-D array so that values lie in [0, 1] using min-max normalization.

In [19]:
arr = np.array([2.0, 5.0, 1.0, 8.0, 3.0])

ans = (arr - arr.min()) / (arr.max() - arr.min())
 
print(ans)

[0.14285714 0.57142857 0.         1.         0.28571429]


### Q22. Compute the column-wise mean of a 4×3 matrix.

In [20]:
arr = np.array([
                    [1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12]
                ])

ans = arr.mean(axis=0)

print(ans)

[5.5 6.5 7.5]


### Q23. Compute the cumulative sum of `[1, 2, 3, 4, 5]`.

In [21]:
arr = np.array([1, 2, 3, 4, 5])

ans = np.cumsum(arr)

print(ans)

[ 1  3  6 10 15]


### Q24. Find the indices of the **top-3** largest values in a 1-D array.

In [22]:
arr = np.array([12, 7, 45, 3, 99, 23, 67])

ans=np.argsort(arr)[-3:][::-1]

print(ans, arr[ans])

[4 6 2] [99 67 45]


### Q25. Compute the standard deviation of each **row** of a 3×4 matrix.

In [25]:
np.random.seed(7)
arr = np.random.randint(1, 20, (3, 4))
print("Original :\n",arr)
ans = arr.std(axis=1)

print("Deviation:\n",ans)

Original :
 [[16  5  4  8]
 [15  9 15 11]
 [ 9  8  7  5]]
Deviation:
 [4.71036092 2.59807621 1.47901995]


### Q26. Compute the **dot product** of two 1-D arrays `[1, 2, 3]` and `[4, 5, 6]`.

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
ans = np.dot(a, b)
print(ans) 

32


In [ ]:
# ✅ Solution
#  # 32

### Q27. Compute the **median** of a 2-D array along axis=1.

In [29]:
arr = np.array([[1, 3, 5, 7],
                [2, 4, 6, 8],
                [9, 11, 13, 15]])

ans = np.median(arr, axis=1)

print(ans)

[ 4.  5. 12.]


### Q28. Round all elements of an array to 2 decimal places.

In [32]:
np.random.seed(0)
arr = np.random.randn(5)
print('Before:\n', arr)

ans = np.round(arr, 2)

print("After:\n",ans)

Before:
 [1.76405235 0.40015721 0.97873798 2.2408932  1.86755799]
After:
 [1.76 0.4  0.98 2.24 1.87]


### Q29. Compute the **percentile** values at 25%, 50%, and 75% for `np.arange(1, 101)`.

In [34]:
arr = np.arange(1, 101)
print("Array:\n",arr)
ans = np.percentile(arr, [25, 50, 75])

print("Percentile Values:\n",ans)

Array:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Percentile Values:
 [25.75 50.5  75.25]


### Q30. Compute the **element-wise** product of two 3×3 matrices (Hadamard product).

In [35]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

c= A * B
print(c)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


---
## 🔵 Section 4 — Reshaping & Broadcasting (Q31–Q40)

### Q31. Subtract the row-wise mean from each row of a 3×4 matrix (mean-center rows).

In [36]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=float)

ans = arr - arr.mean(axis=1, keepdims=True)

print(ans)

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


### Q32. Flatten a 3-D array of shape (2, 3, 4) into a 1-D array.

In [41]:
arr = np.arange(24).reshape(2, 3, 4)
print(arr,"\n")
ans = arr.flatten()  # or arr.ravel()

print("Shape:",ans.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

Shape: (24,)


### Q33. Add a column vector `[10, 20, 30]` to every column of a 3×4 matrix using broadcasting.

In [44]:
matrix = np.zeros((3, 4), dtype=int)
print("MAtrix:\n",matrix)
col = np.array([10, 20, 30])

print("Column:\n",col)

ans = matrix + col.reshape(-1, 1)
print("Reshaped:\n",ans)

MAtrix:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Column:
 [10 20 30]
Reshaped:
 [[10 10 10 10]
 [20 20 20 20]
 [30 30 30 30]]


### Q34. Transpose a 2-D matrix and verify the shape changes.

In [45]:
arr = np.arange(12).reshape(3, 4)
print('Original shape:', arr.shape)
ans = arr.T
print('Transposed shape:', ans.shape)

Original shape: (3, 4)
Transposed shape: (4, 3)


### Q35. Convert a (4,) shaped row vector to a (4, 1) column vector.

In [48]:
arr = np.array([1, 2, 3, 4])
ans = arr[:, np.newaxis]  # or arr.reshape(-1, 1)

print(ans.shape)

(4, 1)


### Q36. Split a (6, 4) matrix into 3 equal sub-arrays along axis 0.

In [49]:
arr = np.arange(24).reshape(6, 4)
parts = np.split(arr, 3, axis=0)
for p in parts:
     print(p, p.shape)

[[0 1 2 3]
 [4 5 6 7]] (2, 4)
[[ 8  9 10 11]
 [12 13 14 15]] (2, 4)
[[16 17 18 19]
 [20 21 22 23]] (2, 4)


### Q37. Tile a `[1, 2, 3]` array to create `[1, 2, 3, 1, 2, 3, 1, 2, 3]`.

In [50]:
arr = np.array([1, 2, 3])
ans = np.tile(arr, 3)
print(ans)

[1 2 3 1 2 3 1 2 3]


### Q38. Concatenate three arrays `[1,2]`, `[3,4]`, `[5,6]` along axis=0.

In [51]:
a, b, c = np.array([1,2]), np.array([3,4]), np.array([5,6])

ans = np.concatenate([a, b, c])

print(ans)

[1 2 3 4 5 6]


### Q39. Use `np.expand_dims` to add a new axis at position 0 to a (3, 4) array.

In [54]:
arr = np.ones((3, 4))
print(arr)
print('Original shape:', arr.shape)

ans = np.expand_dims(arr, axis=0)

print('New shape:', ans.shape)  

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Original shape: (3, 4)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
New shape: (1, 3, 4)


### Q40. Outer product: compute the outer product of `[1,2,3]` and `[4,5]`.

In [55]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

ans = np.outer(a, b)

print(ans)

[[ 4  5]
 [ 8 10]
 [12 15]]


---
## 🔴 Section 5 — Linear Algebra & Advanced (Q41–Q50)

### Q41. Compute the **determinant** of a 3×3 matrix.

In [2]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]], dtype=float)
ans = np.linalg.det(A)
print(round(ans, 4))  

-306.0


### Q42. Solve the linear system **Ax = b** where A = [[2,1],[5,7]] and b = [11, 13].

In [5]:
A = np.array([[2, 1], [5, 7]], dtype=float)
b = np.array([11, 13], dtype=float)

x = np.linalg.solve(A, b)
a=np.round(x,3)
print(a)

[ 7.111 -3.222]


### Q43. Compute the **eigenvalues** and **eigenvectors** of a 2×2 symmetric matrix.

In [6]:
A = np.array([[4, 2], [2, 3]], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(A)
print('Eigenvalues:', eigenvalues)
print('Eigenvectors:\n', eigenvectors)

Eigenvalues: [5.56155281 1.43844719]
Eigenvectors:
 [[ 0.78820544 -0.61541221]
 [ 0.61541221  0.78820544]]


### Q44. Compute the **matrix inverse** of a 3×3 matrix and verify A @ A_inv ≈ I.

In [7]:
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]], dtype=float)

A_inv = np.linalg.inv(A)
print(np.allclose(A @ A_inv, np.eye(3)))  

True


### Q45. Compute the **Frobenius norm** of a 3×3 matrix.

In [8]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)

ans = np.linalg.norm(A, 'fro')
print(round(ans, 4))  

16.8819


### Q46. Perform **SVD** (Singular Value Decomposition) on a 3×2 matrix and print the singular values.

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]], dtype=float)

U, S, Vt = np.linalg.svd(A, full_matrices=False)
print('Singular values:', S)

### Q47. Use `np.einsum` to compute the **trace** (sum of diagonal elements) of a square matrix.

In [9]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

ans = np.einsum('ii', A)
print(ans)  

15


### Q48. Draw 1000 samples from a normal distribution (μ=5, σ=2) and verify the sample mean and std are close.

In [10]:
np.random.seed(42)

samples = np.random.normal(loc=5, scale=2, size=1000)
print(f'Mean: {samples.mean():.2f}, Std: {samples.std():.2f}')

Mean: 5.04, Std: 1.96


### Q49. Compute the **pairwise Euclidean distances** between every pair of points in a (5, 2) array **without a loop**.

In [11]:
np.random.seed(3)
points = np.random.rand(5, 2)
print('Points shape:', points.shape)

diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
dist_matrix = np.sqrt((diff ** 2).sum(axis=-1))
print(dist_matrix.round(3))

Points shape: (5, 2)
[[0.    0.326 0.39  0.657 0.566]
 [0.326 0.    0.715 0.346 0.249]
 [0.39  0.715 0.    1.031 0.957]
 [0.657 0.346 1.031 0.    0.245]
 [0.566 0.249 0.957 0.245 0.   ]]


### Q50. 🏆 BOSS LEVEL — Implement **1-step of K-Means update** using only NumPy:
Given data points and initial centroids, assign each point to the nearest centroid and recompute centroid positions.

In [12]:
np.random.seed(0)
data = np.random.rand(10, 2)          # 10 points in 2D
centroids = data[[0, 5]]              # 2 initial centroids
print('Data shape:', data.shape)
print('Centroids:\n', centroids)

diffs = data[:, np.newaxis, :] - centroids[np.newaxis, :, :]  # (10, 2, 2)
distances = np.sqrt((diffs**2).sum(axis=2))                    # (10, 2)
labels = distances.argmin(axis=1)                              # (10,)
new_centroids = np.array([data[labels == k].mean(axis=0) for k in range(2)])
print('Labels:', labels)
print('New centroids:\n', new_centroids)

Data shape: (10, 2)
Centroids:
 [[0.5488135  0.71518937]
 [0.79172504 0.52889492]]
Labels: [0 0 0 0 1 1 0 0 0 0]
New centroids:
 [[0.43128433 0.6891372 ]
 [0.8776939  0.45616822]]
