## Indexing And Slicing

In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40,50,60])

In [3]:
print(a)


[10 20 30 40 50 60]


### Indexing
    Used to access specific elements

#### Positive Indexing
    Starts from 0

In [4]:
print(a[0])

10


In [5]:
print(a[3])

40


#### Negative Indexing
    Starts from End OR -1
    

In [6]:
print(a[-1])

60


In [8]:
print(a[-2])

50


### Slicing 
    Used to access multiple elements

In [9]:
print(a[1:4])

[20 30 40]


#### Step Slicing
    Return values with step size

In [13]:
print(a[: :2])

[10 30 50]


In [14]:
print(a[: : 3])

[10 40]


#### Negative Slicing

In [16]:
print(a[-3:-1])

[40 50]


In [18]:
print(a[-5:-1 :3])

[20 50]


### Array Operations

In [19]:
b=np.array([2,3,4,6,4,2])

In [20]:
print(b)

[2 3 4 6 4 2]


#### (b + 2) Added each element of b

In [21]:
print(b + 2)

[4 5 6 8 6 4]


#### (b - 2) Subtract each element of b

In [22]:
print(b - 2)

[0 1 2 4 2 0]


#### (b * 3) Multply each element of b

In [24]:
print(b * 3)

[ 6  9 12 18 12  6]


#### (b / 2) Divide each element of b

In [25]:
print(b / 2)

[1.  1.5 2.  3.  2.  1. ]


#### (b % 2)  Each element of b Gives Remainder(Modulo)

In [26]:
print(b % 2)

[0 1 0 0 0 0]
