## Iteration,Looping and Fancy,Advanced Indexing

In [1]:
import numpy as np


### Iterate 1D Arrays

In [2]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

#### Loop runs through every element

In [3]:
for i in a:
    print(i)

10
20
30
40
50


### Iterate 2D arrays

In [5]:
b=np.array([ [1,2],
             [3,4] 
           ] )
for i in b:
    print(i)
 #Each Row is printed          

[1 2]
[3 4]


In [8]:
#Individual Elements
for row in b:
    for element in row:
        print(element)

1
2
3
4


### Iterate 3D Arrays

In [13]:
a=np.array([ [ [1,2],
               [3,4]
             ],
            [  [5,6],
               [7,8]
            ]
           ] )
#Gives one 2D arrays
for layer in a:
    print(layer)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


#### Iterate Rows

In [14]:

for layer in a:
    for row in layer:
        print(row)

[1 2]
[3 4]
[5 6]
[7 8]


#### Iterate Individual Elements

In [16]:
for layer in a:
    for row in layer:
        for element in row:
            print(element)

1
2
3
4
5
6
7
8


### nditer()
    Iterates every element easily

In [17]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8


### enumerate()
    Gives index and value together

In [19]:
a=np.array([10,20,30,40,50])
for index,value in enumerate(a):
    print(index,value)

0 10
1 20
2 30
3 40
4 50


### Pracice Task

In [20]:
import numpy as np

marks = np.array([78,85,90,67])

print("Student Marks:")

for i in marks:
    print(i)

print("Index and Marks:")

for index,value in enumerate(marks):
    print(index,value)

Student Marks:
78
85
90
67
Index and Marks:
0 78
1 85
2 90
3 67


### Fancy indexing
    Selecting multiple elements using index list

In [22]:
a8=np.array([10,20,30,40,50,60])
print(a[ [0,2,4] ]) # 0,2,4 here index numbers

[10 30 50]


### Boolean Indexing
    Returns values satisfy conditions

In [25]:
print(a8[a8>15])

[20 30 40 50 60]


### Multiple conditions

In [26]:
print( (a8>20) & (a8<60))

[False False  True  True  True False]


### Fancy in 2D 

In [29]:
aa8=np.arange(1,10).reshape(3,3)
aa8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
print(aa8[ [0,2] ]) #selected row 0 and row 2

[[1 2 3]
 [7 8 9]]


### Where
    Gives position where value satisfy condition

In [33]:
c=np.array([10,20,30,40,50,60])
print(np.where(c > 30 ))

(array([3, 4, 5]),)


### Fancy in 3D

In [34]:
a = np.array([
    [
        [1,2],
        [3,4]
    ],

    [
        [5,6],
        [7,8]
    ]
])
print(a[1,0,1]) #Access single element

6


#### Access 0 and 1 Layers

In [35]:
print(a[[0,1]]) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Where in 3D

In [36]:
print(np.where(a > 4)) 

(array([1, 1, 1, 1]), array([0, 0, 1, 1]), array([0, 1, 0, 1]))


#### Select specific element

In [37]:
print(a[[0,1],[1,0],[0,1]])

[3 6]


### Pracice Task

In [38]:
import numpy as np

marks = np.array([45,67,89,90,34,76,55])

print("Top Scorers:")
print(marks[marks > 80])

print("Average Students:")
print(marks[(marks >= 50) & (marks <= 80)])

print("Indexes Above 70:")
print(np.where(marks > 70))

Top Scorers:
[89 90]
Average Students:
[67 76 55]
Indexes Above 70:
(array([2, 3, 5]),)
