## Functions 

In [1]:
import numpy as np

In [2]:
a=np.array([10,50,23,45,36])
a

array([10, 50, 23, 45, 36])

### 1.sort()
    Arrange elements in ascending order

In [3]:
print(np.sort(a))

[10 23 36 45 50]


In [4]:
#Descending order Reverse the array
print(np.sort(a)[: : -1])

[50 45 36 23 10]


### 2.argsort()
    Returns indexes of sorted elements

In [5]:
print(np.argsort(a))

[0 2 4 3 1]


### 3.searchsorted()
    Finds insertion position with ascending order

In [6]:
c=np.array([10,50,23,45,36])
print(np.searchsorted(c,24))

3


### 4.nonzero()
    Leaves the 0 index and gives other indesx

In [8]:
a=np.array([0,2,4,5,0,6])
print(np.nonzero(a))

(array([1, 2, 3, 5]),)


### 5.extract()
    Condition matched elements are given

In [10]:
a=np.array([0,2,4,5,0,6,7,8,9])
print(np.extract(a>4,a))

[5 6 7 8 9]


### 6.unique()
    Returns only unique values
    

In [12]:
a=np.array([0,2,4,2,5,6,7,5,0,6])
print(np.unique(a))

[0 2 4 5 6 7]


### 7.any()
    Checks if atleast one condition is true

In [17]:
a=np.array([0,0,0,0,6])
print("One non zero element:\n",np.any(a))

a=np.array([0,0,0,0])
print("All zeros:\n",np.any(a))

One non zero element:
 True
All zeros:
 False


### 8.all()
    Checks if all values are true

In [18]:
c=np.array([10,50,23,45,36])
print("All are non zero:\n",np.all(c))

c=np.array([10,0,23,0,36])
print("If atleast zero:\n",np.all(c))

All are non zero:
 True
If atleast zero:
 False


### 9.append()
    Adds new element at ends

In [19]:
c=np.array([10,50,23,45,36])
print("Original array:\n",c)

print("Added Element:\n",np.append(c,100))

Original array:
 [10 50 23 45 36]
Added Element:
 [ 10  50  23  45  36 100]


### 10.insert()
    Adds value at specific positions


In [21]:
c=np.array([10,50,23,45,36])
print("Original array:\n",c)

print("Added Element at postion 1:\n",np.insert(c,1,100))

Original array:
 [10 50 23 45 36]
Added Element at postion 1:
 [ 10 100  50  23  45  36]


### 11.delete()
    Remove value using index

In [22]:
c=np.array([10,50,23,45,36])
print("Original array:\n",c)

print("Element deleted from index 1:\n",np.delete(c,1))

Original array:
 [10 50 23 45 36]
Element deleted from index 1:
 [10 23 45 36]


### Practice Task

In [23]:
import numpy as np

roll = np.array([101,102,102,103,104])

print("Unique Roll Numbers:")
print(np.unique(roll))

print("Append:")
print(np.append(roll,105))

print("Insert:")
print(np.insert(roll,2,999))

print("Delete:")
print(np.delete(roll,1))

Unique Roll Numbers:
[101 102 103 104]
Append:
[101 102 102 103 104 105]
Insert:
[101 102 999 102 103 104]
Delete:
[101 102 103 104]


## Bitwisw Functions
    Operations work on binary numbers (0 And 1)

### 1.bitwise_and()
    Returns true only if both bits are 1

In [33]:
print(np.bitwise_and(5,3)) #True case Binary bits(5 = 1 0 1 AND 3 = 0 1 1)
                                      

print(np.bitwise_and(2,1)) #False case

1
0


### 2.bitwise_or()
    Returns true if any one bit is 1

In [32]:
print(np.bitwise_or(5,3)) #True case

print(np.bitwise_or(0,0)) #False case

7
0


### 3.bitwise_xor
    Returns true if bits are different

In [34]:
print(np.bitwise_xor(5,3)) #True case

print(np.bitwise_xor(2,2)) #False case

6
0


### 4.invert()
    Flips the  bits ,Change 1 To 0 and 0 To 1

In [39]:
print(np.invert(5)) # binary bits(5 = 0000101 ) Inverted To 1111010


-6


### 5.left_shift()
    Shift bits to left 
    

In [49]:
print(np.left_shift(5,1)) #Bit Postion shifted by 1

print(np.left_shift(5,2)) #Bit Postion shifted by 2

10
20


### 6.right_shift()
    Shift bits to  right

In [50]:
print(np.right_shift(5,1)) #Bit Postion shifted by 1

print(np.right_shift(5,2)) #Bit Postion shifted by 2

2
1


In [51]:
import numpy as np

print("AND:", np.bitwise_and(6,3))

print("OR:", np.bitwise_or(6,3))

print("XOR:", np.bitwise_xor(6,3))

print("LEFT SHIFT:", np.left_shift(6,1))

print("RIGHT SHIFT:", np.right_shift(6,1))

AND: 2
OR: 7
XOR: 5
LEFT SHIFT: 12
RIGHT SHIFT: 3
