## Array Operations

In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40])

In [3]:
print(a)

[10 20 30 40]


In [5]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

### Arithmetic Operations

#### 1.Addition

In [6]:
print(a+b)

[11 22 33 44]


#### 2.Subtraction

In [8]:
print(a-b)

[ 9 18 27 36]


#### 3.Multiplecation

In [9]:
print(a * b)

[ 10  40  90 160]


#### 4.Divide 

In [10]:
print(a /b)

[10. 10. 10. 10.]


#### 5.Modulus

In [11]:
print(a % b)

[0 0 0 0]


#### 6.Power

In [12]:
print(b ** 2)

[ 1  4  9 16]


#### 7.cube

In [13]:
print(b ** 3)

[ 1  8 27 64]


### Scalar Operations

In [14]:
print(a + 5)

[15 25 35 45]


In [15]:
print(b * 10)

[10 20 30 40]


### Practice Task

In [23]:
import numpy as np

salary = np.array([25000,30000,35000,40000])

bonus = np.array([2000,3000,4000,5000])

print("Updated Salary:")
print(salary + bonus)

print("Double Salary:")
print(salary * 2)

print("Half Salary:")
print(salary / 2)

print("Salary Square:")
print(salary ** 2)

Updated Salary:
[27000 33000 39000 45000]
Double Salary:
[50000 60000 70000 80000]
Half Salary:
[12500. 15000. 17500. 20000.]
Salary Square:
[ 625000000  900000000 1225000000 1600000000]


#### Create two arrays and perform addition.

In [24]:
a=np.array([10,20,30,40])

b=np.array([5,10,15,20])

print(a + b)

[15 30 45 60]


#### Multiply array by 5

In [26]:
print("Multiply 5 By Each Array of a",a * 5)

Multiply 5 By Each Array of a [ 50 100 150 200]


#### Find square of array elements.

In [27]:
print("Square of array Elemtns:",a ** 2)

Square of array Elemtns: [ 100  400  900 1600]


### Comparison Operations

#### 1.Greater Than 

In [16]:
print(a > 30)

[False False False  True]


### 2.Less Than

In [17]:
print(a < 30)

[ True  True False False]


#### 3.Equal To

In [18]:
print(a == 40)

[False False False  True]


#### 4.Greater Than or Equal To

In [19]:
print(a >= 30)

[False False  True  True]


#### 5.Less Than or Equal To

In [21]:
print(a <= 30)

[ True  True  True False]


#### 6.Not Equal To
    Reverse The Result

In [22]:
print(a !=30)

[ True  True False  True]


#### 7.Logical AND

In [30]:
print((a > 20) & (a < 50))

[False False  True  True]


#### 8.Logical OR

In [33]:
print((a < 20) | (a > 30))

[ True False False  True]


#### 9.Logical NOT

In [34]:
print(~(a>20))

[ True  True False False]


#### 10.Filtering
    Returns only values satisfying condition.

In [35]:
print(a[a > 25])

[30 40]


### Practice Task

In [37]:
import numpy as np

marks = np.array([20,45,67,89,90,34,76,55])

print("Passed Students:")
print(marks[marks >= 40])

print("Top Scorers:")
print(marks[marks > 80])

print("Average Students:")
print(marks[(marks >= 50) & (marks <= 80)])

Passed Students:
[45 67 89 90 76 55]
Top Scorers:
[89 90]
Average Students:
[67 76 55]


#### Print values between 20 and 55

In [45]:
print(marks[(marks >= 20) & (marks <= 55)])


[20 45 34 55]
