## Broadcasting And Copy VS View 

In [39]:
import numpy as np

### 1.Scalar Broadcasting

In [50]:
a=np.array([1,2,3])
print(a + 5)

[6 7 8]


#### For 2D Arrays

In [51]:
b=np.arange(11,17).reshape(2,3)
print("B Array:\n",b,"\n")
print("Broadcasting:\n",b + a)

B Array:
 [[11 12 13]
 [14 15 16]] 

Broadcasting:
 [[12 14 16]
 [15 17 19]]


#### If Error When Shape not Compatible 

In [52]:
a=np.array([1,2,3,4])  # Array Size (4, )
a


array([1, 2, 3, 4])

In [54]:
b=np.arange(11,17).reshape(2,3) # Array Size (2,3)
print("B Array:\n",b,"\n")
print("Broadcasting:\n",b + a)

B Array:
 [[11 12 13]
 [14 15 16]] 



ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

### Practice Task

In [62]:
import numpy as np

marks = np.array([
    [70,80,90],
    [60,75,85]
])

bonus = np.array([5,5,5])

print("Updated Marks:")
print(marks + bonus)

Updated Marks:
[[75 85 95]
 [65 80 90]]


### Copy()
    Creates completely separate array
    Original arrays does not change

In [55]:
a=np.array([1,2,3,4])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3 4]
[100   2   3   4]


### View() 
    Share Arrays same Memory
    Original array also change

In [57]:
a=np.array([1,2,3,4])
b=a.view()
b[0]=100
print(a)
print(b)

[100   2   3   4]
[100   2   3   4]


### Base Attribute
        Tells that whether array owns data or share memory

In [59]:
a=np.array([1,2,3,4])
b=a.view()
print(b.base) # b is connected to a

[1 2 3 4]


In [61]:
a=np.array([1,2,3,4])
c=a.copy()
print(c.base) # c is Independent

None


### Practice Task

In [63]:
import numpy as np

arr = np.array([10,20,30])

copy_arr = arr.copy()

view_arr = arr.view()

copy_arr[0] = 999

view_arr[1] = 777

print("Original:", arr)

print("Copy:", copy_arr)

print("View:", view_arr)

Original: [ 10 777  30]
Copy: [999  20  30]
View: [ 10 777  30]
