## 2 Dimensions & 3 Dimensions Arrays

In [1]:
import numpy as np

### 2D Arrays

In [3]:
a=np.array([ 
                [5,6,7],
                [2,3,1] ])

In [4]:
print(a)

[[5 6 7]
 [2 3 1]]


#### Checks Shape of Array

In [5]:
print(a.shape)

(2, 3)


#### Checks Dimensions

In [6]:
print(a.ndim)

2


#### 2D Indexing

In [7]:
print(a[0,1])

6


#### Access 1 Row and 2 Column

In [8]:
print(a[1,2])

1


#### Slicing in 2D Array

In [9]:
print(a[:,1])

[6 3]


#### Reshaping Arrays

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)

print(reshaped)

[[1 2 3]
 [4 5 6]]


#### Iterating Through 2D Array Using Loop

In [11]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for row in arr:
    print(row)

[1 2 3]
[4 5 6]


#### Iterating each element

In [12]:
for row in arr:
    for element in row:
        print(element)

1
2
3
4
5
6


#### Random array example

In [13]:
random_array = np.random.randint(1, 100, size=(2, 3))

print(random_array)

[[89 97  9]
 [44 35 17]]


In [14]:
random_array = np.random.randint(1, 100, size=(2, 3))

print(random_array)

[[68 58 28]
 [85 87 90]]


#### 2D Task

In [22]:
import numpy as np

marks = np.array([
    [78,85,90],
    [67,88,92],
    [75,80,95]
])

print("Marks Table:")
print(marks)

print("Shape:", marks.shape)

print("Dimensions:", marks.ndim)

print("First Student Marks:", marks[0])

print("Math Marks:", marks[:,0])

print("Science Marks:", marks[:,1])

print("Computer Marks:", marks[:,2])

Marks Table:
[[78 85 90]
 [67 88 92]
 [75 80 95]]
Shape: (3, 3)
Dimensions: 2
First Student Marks: [78 85 90]
Math Marks: [78 67 75]
Science Marks: [85 88 80]
Computer Marks: [90 92 95]


### Array with 3 Rows And 3 Columns

In [23]:
arr3=np.random.randint(1, 100, size=(3, 3))
print(arr3)

[[19 47 15]
 [62 80  9]
 [54 83 59]]


#### Access element 83 from array.

In [24]:
print(arr3[2,1])

83


#### Print second column from array.

In [27]:
print(arr3[:,1])

[47 80 83]


### 3D Arrays

In [21]:
arr_3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Check Shape of 3D Array

In [16]:
print(arr_3d.shape)

(2, 2, 3)


### Check Dimension

In [17]:
print(arr_3d.ndim)

3


#### Accessing 3D arrays

In [18]:
print(arr_3d[1, 0, 2])

9


#### Iterating Through 3D Array Using Loop

In [20]:
arr_3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])
for i in arr_3d:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


#### 3D Task

In [28]:
import numpy as np

data = np.array([
    [
        [10,20],
        [30,40]
    ],

    [
        [50,60],
        [70,80]
    ]
])

print("3D Array:")
print(data)

print("Dimensions:", data.ndim)

print("Shape:", data.shape)

print("Value 60:", data[1,0,1])

print("Value 30:", data[0,1,0])

3D Array:
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
Dimensions: 3
Shape: (2, 2, 2)
Value 60: 60
Value 30: 30


#### Create a 3D array with values from 1 to 8.

In [30]:
a4=np.arange(1, 9).reshape(2,2,2) 
print(a4)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Print element 7 from array.

In [31]:
print("Value 7:", a4[1,1,0])

Value 7: 7
